### PR TITLE
Separate generated files

### PR DESCRIPTION
**Pull request by JonnyBGod**
Support for separate file generators.

Extra changes:
- Included cli in this project, I don't see why we need a separate repo for the cli.
- renamed generators as angularjs for angular1 and angular for angular2 this makes it similar to current project names.
- Angular generator now generates separate files and models (models are in early development stage as it need more testing and better support for types)

### CODE REVIEW

**Comment by JonnyBGod** [comment]
This is a bit messy. I was in a bit of a rush and needed something working.

You might prefer using this PR as a reference for your own implementation.

**Comment by jonathan-casarrubias** [comment]
Hey @JonnyBGod, I will check it later today, is great to see you manage to separate the models into files.

I will verify and test it so I can provide some feedback and merge it if possible.

Cheers!
Jon

**Comment by JonnyBGod** [comment]
Finished angular 2 templates. It should generate a working service now.

**Comment by jonathan-casarrubias** [comment]
I reviewed your work and its an amazing contribution.

Integrating...

**Comment by jonathan-casarrubias** [comment]
I just published your changes under version 1.6.11.

Some thoughts... many of the templates can be moved to a common folder. I will dedicate time this weekend to create the common folder and port your contributions to the nativescript one.

Happy coding!! @JonnyBGod

**Comment by JonnyBGod** [comment]
Thanks.

I agree with you. Models for instance could be moved to common at least for every typescript generator.

**Pull request merged**
